# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-23 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_stburls',
            fields=[
                ('pkid', models.AutoField(primary_key=True, serialize=False)),
                ('stbnum', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=256)),
            ],
        ),
    ]
